version: 2.1

executors:
  python-executor:
    docker:
      - image: python:3.8

jobs:
  test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies for testing notebooks
          command: |
            pip install --upgrade pip
            pip install nbconvert ipykernel
      - run:
          name: Install the sampling_simulator package
          command: |
            pip3 install .
      - run:
          name: Test notebooks
          command: |
            # For some reason, I had to same the .py files in the home directory of the project
            # to be able to run `from sampling_simulator.utils import utils` ...
            for notebook in examples/*.ipynb; do
              base_name=$(basename "$notebook" .ipynb)
              jupyter nbconvert --to script "$notebook" --output-dir='.'
              python "${base_name}.py"
              rm "${base_name}.py"
            done

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
