version: 2.1

executors:
  python-executor:
    docker:
      - image: python:3.8

jobs:
  test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies for testing notebooks
          command: |
            pip install --upgrade pip
            pip install nbconvert ipykernel
      - run:
          name: Install the sampling_simulator package
          command: |
            pip3 install .
      - run:
          name: Test notebooks
          command: |
            for notebook in examples/*.ipynb; do
              jupyter nbconvert --to notebook --execute --inplace "$notebook"
              if [ $? -ne 0 ]; then
                echo "Error in $notebook"
                exit 1
              fi
            done

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
